import Alphabets from "./Alphabets";
import AlphabetsDetails from "./AlphabetsDetails";
import Home from "./Home";
import Layout from "./Layout";
import Layout_Admin from "./Layout_Admin";
import SignIn from "./SignIn";
import Signup from "./Signup";
import Welcome from "./Welcome";
import WordGame from "./WordGame/WordGame";
import WritingBoard from "./WritingBoard";
import Dashboard from "./admin/Dashboard";
import ArAllAlphabet from "./admin/arabic/ArAllAlphabet";
import ArUpdateAlphabet from "./admin/arabic/ArUpdateAlphabet";
import BnAllAlphabet from "./admin/bangla/BnAllAlphabet";
import BnUpdateAlphabet from "./admin/bangla/BnUpdateAlphabet";
import Days from "./admin/day/Days";
import DaysUpdate from "./admin/day/DaysUpdate";
import EnAllAlphabet from "./admin/english/EnAllAlphabet";
import EnUpdateAlphabet from "./admin/english/EnUpdateAlphabet";
import MonthUpdate from "./admin/month/MonthUpdate";
import Months from "./admin/month/Months";
import Number from "./admin/number/Number";
import NumberUpdate from "./admin/number/NumberUpdate";
import SeasonUpdate from "./admin/season/SeasonUpdate";
import Seasons from "./admin/season/Seasons";
import Arabic from "./arabic/Arabic";
import Bangla from "./bangla/Bangla";
import English from "./english/English";
import Mathematics from "./math/Math";
import WhiteBoard from "./whiteBoard/WhiteBoard";

export { Alphabets, AlphabetsDetails, ArAllAlphabet, ArUpdateAlphabet, Arabic, Bangla, BnAllAlphabet, BnUpdateAlphabet, Dashboard, Days, DaysUpdate, EnAllAlphabet, EnUpdateAlphabet, English, Home, Layout, Layout_Admin, Mathematics, MonthUpdate, Months, Number, NumberUpdate, SeasonUpdate, Seasons, SignIn, Signup, Welcome, WhiteBoard, WordGame, WritingBoard };

